project:
  type: website
  output-dir: docs

website:
  title: "From Data to Decisions | Dev Karan Gur"
  site-url: "https://etc5523-2025.github.io/assignment-3-creating-a-blog-devgur1/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/devgur1
format:
  html:
    theme: cosmo
    css: styles.css



