project:
  type: website

website:
  title: "Dev Karan Gur — Communicating with Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/devgur1
format:
  html:
    theme: cosmo
    css: styles.css



