project:
  type: website
  output-dir: docs

website:
  title: "From Data to Decisions | Dev Karan Gur"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/devgur1
format:
  html:
    theme: cosmo
    css: styles.css



